Search.setIndex({
  alltitles: {
    "1. Copyright and Related Rights.": [[8, "copyright-and-related-rights"]],
    "2-Clause BSD license / FreeBSD license": [[3, null]],
    "2. Waiver.": [[8, "waiver"]],
    "3. Public License Fallback.": [[8, "public-license-fallback"]],
    "4. Limitations and Disclaimers.": [[8, "limitations-and-disclaimers"]],
    "Assignment 01: Tensors and Einsum": [[14, null]],
    "Automatic Vendoring": [[7, "automatic-vendoring"]],
    "CC0 1.0 Universal licence": [[8, "cc0-1-0-universal-licence"]],
    "Copying Docutils": [[1, null]],
    Debundling: [[7, "debundling"]],
    Exceptions: [[1, "exceptions"]],
    Licence: [[8, null]],
    "License for Sphinx": [[9, null]],
    "MLA documentation": [[15, null]],
    "Managing Local Patches": [[7, "managing-local-patches"]],
    Modifications: [[7, "modifications"]],
    "Optional Task: Tensor Permutation and Reshaping": [
      [14, "optional-task-tensor-permutation-and-reshaping"],
    ],
    "Public Domain Dedication": [[1, "public-domain-dedication"]],
    Rationale: [[7, "rationale"]],
    "Statement of Purpose": [[8, "statement-of-purpose"]],
    "Task 1: Dot Product": [[14, "task-1-dot-product"]],
    "Task 2: Matrix-Matrix Multiplication": [
      [14, "task-2-matrix-matrix-multiplication"],
    ],
    "Task 3: Einsum acsxp, bspy -> abcxy": [
      [14, "task-3-einsum-acsxp-bspy-abcxy"],
    ],
    "The MIT License (MIT)": [[6, null]],
    "Vendoring Policy": [[7, null]],
    "Zero-Clause BSD": [[2, null]],
    "Zero-Clause BSD Licence": [[8, "zero-clause-bsd-licence"]],
    "docutils/parsers/rst/include Directory": [[4, null]],
  },
  docnames: [
    ".venv/Lib/site-packages/alabaster-1.0.0.dist-info/LICENSE",
    ".venv/Lib/site-packages/docutils-0.22.4.dist-info/licenses/COPYING",
    ".venv/Lib/site-packages/docutils-0.22.4.dist-info/licenses/licenses/BSD-0-Clause",
    ".venv/Lib/site-packages/docutils-0.22.4.dist-info/licenses/licenses/BSD-2-Clause",
    ".venv/Lib/site-packages/docutils/parsers/rst/include/README",
    ".venv/Lib/site-packages/docutils/writers/s5_html/themes/README",
    ".venv/Lib/site-packages/imagesize-2.0.0.dist-info/licenses/LICENSE",
    ".venv/Lib/site-packages/pip/_vendor/README",
    ".venv/Lib/site-packages/roman_numerals-4.1.0.dist-info/licenses/LICENCE",
    ".venv/Lib/site-packages/sphinx-9.1.0.dist-info/licenses/LICENSE",
    ".venv/Lib/site-packages/sphinx/ext/autosummary/templates/autosummary/base",
    ".venv/Lib/site-packages/sphinx/ext/autosummary/templates/autosummary/class",
    ".venv/Lib/site-packages/sphinx/ext/autosummary/templates/autosummary/module",
    ".venv/Lib/site-packages/sphinx/search/minified-js/README",
    "assignments/01_assignment/assignment_01",
    "index",
  ],
  envversion: {
    sphinx: 66,
    "sphinx.domains.c": 3,
    "sphinx.domains.changeset": 1,
    "sphinx.domains.citation": 1,
    "sphinx.domains.cpp": 9,
    "sphinx.domains.index": 1,
    "sphinx.domains.javascript": 3,
    "sphinx.domains.math": 2,
    "sphinx.domains.python": 4,
    "sphinx.domains.rst": 2,
    "sphinx.domains.std": 2,
  },
  filenames: [
    ".venv\\Lib\\site-packages\\alabaster-1.0.0.dist-info\\LICENSE.rst",
    ".venv\\Lib\\site-packages\\docutils-0.22.4.dist-info\\licenses\\COPYING.rst",
    ".venv\\Lib\\site-packages\\docutils-0.22.4.dist-info\\licenses\\licenses\\BSD-0-Clause.rst",
    ".venv\\Lib\\site-packages\\docutils-0.22.4.dist-info\\licenses\\licenses\\BSD-2-Clause.rst",
    ".venv\\Lib\\site-packages\\docutils\\parsers\\rst\\include\\README.rst",
    ".venv\\Lib\\site-packages\\docutils\\writers\\s5_html\\themes\\README.rst",
    ".venv\\Lib\\site-packages\\imagesize-2.0.0.dist-info\\licenses\\LICENSE.rst",
    ".venv\\Lib\\site-packages\\pip\\_vendor\\README.rst",
    ".venv\\Lib\\site-packages\\roman_numerals-4.1.0.dist-info\\licenses\\LICENCE.rst",
    ".venv\\Lib\\site-packages\\sphinx-9.1.0.dist-info\\licenses\\LICENSE.rst",
    ".venv\\Lib\\site-packages\\sphinx\\ext\\autosummary\\templates\\autosummary\\base.rst",
    ".venv\\Lib\\site-packages\\sphinx\\ext\\autosummary\\templates\\autosummary\\class.rst",
    ".venv\\Lib\\site-packages\\sphinx\\ext\\autosummary\\templates\\autosummary\\module.rst",
    ".venv\\Lib\\site-packages\\sphinx\\search\\minified-js\\README.rst",
    "assignments\\01_assignment\\assignment_01.rst",
    "index.rst",
  ],
  indexentries: {},
  objects: {},
  objnames: {},
  objtypes: {},
  terms: {
    "2to3": 7,
    A: [0, 3, 6, 8, 9, 14],
    ALL: [2, 8],
    AN: [2, 6, 8],
    AND: [0, 2, 3, 6, 8, 9],
    ARE: [0, 3, 9],
    AS: [0, 2, 3, 6, 8, 9],
    All: [1, 9, 14],
    As: 7,
    At: 7,
    BE: [0, 2, 3, 6, 8, 9],
    BUT: [0, 3, 6, 9],
    BY: [0, 3, 9],
    FOR: [0, 2, 3, 6, 8, 9],
    FROM: [2, 6, 8],
    For: [1, 5, 8],
    Further: 8,
    How: 14,
    IF: [0, 3, 9],
    IN: [0, 2, 3, 6, 8, 9],
    IS: [0, 2, 3, 6, 8, 9],
    If: 7,
    In: [7, 8, 14],
    It: 7,
    Most: 1,
    NO: [0, 2, 3, 6, 8, 9],
    NOT: [0, 3, 6, 7, 9],
    No: [1, 8, 14],
    OF: [0, 2, 3, 6, 8, 9],
    ON: [0, 3, 9],
    OR: [0, 2, 3, 6, 7, 8, 9],
    OTHER: [2, 6, 8],
    OUT: [0, 2, 3, 6, 8, 9],
    SUCH: [0, 3, 9],
    Should: 8,
    So: 1,
    Some: 0,
    THE: [0, 2, 3, 6, 8, 9],
    THIS: [0, 2, 3, 8, 9],
    TO: [0, 2, 3, 6, 8, 9],
    The: [0, 1, 7, 8, 14],
    There: 1,
    These: [1, 5, 7, 8],
    This: [1, 4, 7, 8, 14],
    To: [4, 7, 8, 14],
    WITH: [2, 6, 8],
    We: 7,
    When: 7,
    You: [7, 14],
    Your: 14,
    __init__: [1, 7],
    __main__: 1,
    _vendor: 7,
    a_: 14,
    a_k: 14,
    abandon: 8,
    abov: [0, 1, 3, 6, 7, 9],
    absenc: 8,
    access: [4, 7],
    accompani: 7,
    account: 8,
    accumul: 14,
    accuraci: 8,
    acknowledg: 8,
    across: 7,
    act: 1,
    action: [2, 6, 8],
    adam: 8,
    adapt: 8,
    add: [7, 15],
    addit: [7, 8],
    advertis: 8,
    advis: [0, 3, 9],
    affect: 8,
    affirm: 8,
    alex: 1,
    alloc: 14,
    allow: [7, 14],
    along: 7,
    alreadi: [7, 14],
    also: 7,
    altern: 7,
    although: 7,
    amend: 8,
    angl: 4,
    ani: [0, 1, 2, 3, 6, 7, 8, 9, 14],
    anoth: 7,
    answer: 14,
    anyon: 1,
    appdir: 7,
    appli: [1, 7, 8],
    applic: [1, 7, 8],
    appropri: 7,
    approv: 1,
    april: 7,
    aris: [0, 2, 3, 6, 8, 9],
    armin: 0,
    around: 4,
    assert: [8, 14],
    assignment_01: 14,
    associ: [1, 6, 8],
    assum: 14,
    assumpt: 7,
    author: [1, 2, 6, 8, 9],
    authorship: [1, 8],
    autom: 7,
    automat: 8,
    avail: [7, 8],
    avoid: 7,
    b: 14,
    b_: 14,
    b_k: 14,
    base: [0, 1, 5, 8, 14],
    battl: 7,
    becaus: 7,
    befor: 14,
    began: 7,
    begin: 1,
    benefit: [1, 7, 8],
    better: 7,
    binari: [0, 3, 9],
    bit: 7,
    block: 12,
    bootstrap: 7,
    bracket: 4,
    branch: 7,
    brought: 7,
    bsd: [1, 9],
    bug: 7,
    build: [7, 8],
    built: 1,
    bundl: 7,
    busi: [0, 3, 9],
    c: [0, 7, 8, 9, 14],
    c_: 14,
    cacert: 7,
    cachecontrol: 7,
    call: 14,
    can: [7, 8, 14],
    cancel: 8,
    case: [7, 8],
    caus: [0, 3, 8, 9],
    cc: 1,
    cc0: 1,
    cdot: 14,
    ceas: 7,
    central: 7,
    certain: [7, 8],
    chad: 1,
    chang: [7, 14],
    charg: 6,
    check: 14,
    choos: 7,
    ci: 7,
    claim: [6, 8],
    claus: [1, 9],
    clean: 7,
    clear: 8,
    cli: 1,
    code: [0, 1, 3, 7, 9, 14],
    com: 5,
    command: 7,
    commerci: [1, 8],
    commit: 7,
    common: [1, 8],
    commonmark_wrapp: 1,
    communic: 8,
    compat: [1, 7],
    compens: 8,
    competit: 8,
    compil: 7,
    complet: 7,
    complic: 7,
    compress: 13,
    comput: 14,
    conceiv: 1,
    concern: 8,
    condit: [0, 3, 6, 9],
    confer: 8,
    configur: 7,
    connect: [2, 6, 8],
    consent: 8,
    consequenti: [0, 2, 3, 8, 9],
    consid: 7,
    consider: 8,
    consist: 1,
    contact: 1,
    contain: [4, 7],
    contempl: 8,
    content: [7, 15],
    conting: 1,
    contract: [0, 2, 3, 6, 8, 9],
    contrari: 8,
    contravent: 8,
    contribut: 8,
    contributor: [0, 1, 3, 9],
    copi: [2, 6, 7, 8],
    copyright: [0, 1, 3, 6, 9],
    correct: 7,
    correspond: [7, 8, 14],
    council: 8,
    cours: 7,
    creat: 14,
    creativ: [1, 8],
    creator: 8,
    credit: 5,
    css: 1,
    cultur: 8,
    current: [7, 8],
    d: [7, 14],
    damag: [0, 2, 3, 6, 8, 9],
    data: [0, 2, 3, 4, 8, 9, 14],
    databas: 8,
    date: [1, 8],
    david: 1,
    deal: 6,
    declar: 1,
    deem: 8,
    default: 7,
    defect: 8,
    defin: [7, 8, 14],
    definit: 4,
    delet: 7,
    depend: 7,
    depict: 8,
    deriv: [0, 1],
    describ: 7,
    detail: [4, 5, 15],
    detect: 7,
    determin: 7,
    detriment: [1, 8],
    diff: 7,
    differ: [1, 7, 14],
    dimens: 14,
    direct: [0, 2, 3, 4, 8, 9],
    directori: [1, 5, 7],
    disclaim: [0, 2, 3, 9],
    discov: 7,
    discover: 8,
    display: 8,
    disrupt: 8,
    dissemin: 8,
    dist: 7,
    distribut: [0, 1, 2, 3, 6, 7, 8, 9],
    document: [0, 1, 3, 4, 6, 8, 9, 14],
    doe: [1, 14],
    doesn: 7,
    domain: 5,
    don: 7,
    done: [7, 13],
    dot_product: 14,
    downstream: 7,
    dtd: 1,
    due: 7,
    duplic: 7,
    durat: 8,
    duti: 8,
    easier: 7,
    ec: 8,
    echo: 13,
    editor: 1,
    effect: 8,
    effort: 8,
    einsum_gemm: 14,
    einsum_loop: 14,
    either: [7, 8],
    el: 1,
    elect: 8,
    element: 14,
    elyx: 1,
    emac: 1,
    end: 7,
    endblock: 12,
    endfor: 12,
    endif: 12,
    endors: 0,
    enforc: 1,
    enjoy: 8,
    ensur: 7,
    entir: 1,
    entri: 7,
    equit: 8,
    equival: 8,
    eric: 5,
    error: 8,
    error_report: 1,
    escap: [10, 11, 12],
    etc: 1,
    european: 8,
    even: [0, 3, 7, 9],
    event: [0, 2, 3, 6, 8, 9],
    ever: 7,
    everi: 7,
    everyth: 7,
    except: [5, 7],
    exclus: 8,
    execut: 7,
    exemplari: [0, 3, 9],
    exercis: 8,
    exist: [7, 8],
    expect: [7, 8],
    experi: 14,
    exploit: 1,
    express: [0, 3, 6, 8, 9],
    extens: 8,
    extent: 8,
    extern: 7,
    extra: 7,
    extract: 8,
    f: 13,
    fail: 7,
    fair: 7,
    far: 7,
    faster: 7,
    fear: 8,
    featur: 7,
    fee: [2, 8],
    "fern\u00e1ndez": 1,
    file: [1, 4, 5, 6, 7, 9, 13, 14],
    filesystem: 7,
    first: 7,
    fit: [0, 2, 3, 6, 8, 9],
    fix: 7,
    follow: [0, 3, 6, 7, 8, 9, 14],
    forc: 7,
    forcier: 0,
    form: [0, 1, 3, 8, 9],
    foundat: 1,
    fragil: 7,
    free: [1, 6, 8],
    freeli: [1, 8],
    fresh: 14,
    fulli: 8,
    fullnam: [10, 11, 12],
    function: [7, 14],
    furnish: 6,
    futur: [1, 8],
    g: 13,
    gain: 8,
    general: 1,
    generat: 7,
    git: 7,
    given: [7, 14],
    glanc: 7,
    global: 7,
    gnu: 1,
    good: [0, 3, 9],
    goodger: 1,
    gpl: 1,
    grant: [2, 6, 8],
    great: 7,
    greater: 8,
    greatest: 8,
    gruber: 1,
    "g\u00fcnter": 1,
    hand: 7,
    handl: [7, 14],
    happi: 7,
    header: 14,
    heir: [1, 8],
    held: 8,
    herebi: [1, 2, 6, 8],
    higher: 7,
    hint: 14,
    histor: 7,
    hold: 7,
    holder: [0, 3, 6, 9],
    howev: [0, 3, 7, 9],
    html: 5,
    html5_polyglot: 1,
    http: [1, 5],
    https: [1, 7],
    ideal: 8,
    identifi: 1,
    ii: 8,
    iii: 8,
    imag: 8,
    implement: [7, 8, 14],
    impli: [0, 2, 3, 6, 8, 9],
    import: 7,
    inc: 1,
    incident: [0, 3, 9],
    includ: [0, 1, 2, 3, 6, 7, 8, 9],
    inclus: [1, 4],
    incompat: 7,
    incomplet: 7,
    incorpor: 8,
    independ: 7,
    index: 14,
    indic: 9,
    indirect: [0, 2, 3, 8, 9],
    ineffect: 8,
    info: 7,
    infring: 8,
    initi: 14,
    input: 14,
    insid: [7, 14],
    insist: 7,
    instal: [7, 13],
    install_requir: 7,
    instead: 7,
    intact: 7,
    integr: 7,
    intend: [1, 4, 8],
    interfac: 1,
    internet: 1,
    interrupt: [0, 3, 9],
    invalid: 8,
    invent: 1,
    io: 1,
    irrevoc: 8,
    is_contigu: 14,
    isn: 7,
    isonum: 4,
    issu: 7,
    item: 12,
    iter: 14,
    iv: 8,
    jeff: 0,
    jen: 1,
    john: 1,
    js: 13,
    judg: 8,
    jurisdict: 8,
    just: 14,
    "j\u00f8rgen": 1,
    k: 14,
    keep: 7,
    kenneth: 0,
    kind: [6, 7, 8],
    know: 7,
    knowledg: 8,
    known: [1, 8],
    lack: 7,
    larg: [1, 8],
    latent: 8,
    later: [1, 8],
    latest: 7,
    latex2: 1,
    latex2mathml: 1,
    launch: 7,
    law: [1, 8],
    lawsuit: 1,
    leav: 7,
    left: 7,
    legal: [1, 8],
    length: 14,
    less: [1, 7],
    liabil: [0, 3, 6, 9],
    liabl: [0, 2, 3, 6, 8, 9],
    librari: 7,
    library_nam: 7,
    licenc: 9,
    licens: [1, 7],
    like: [7, 8],
    limit: [0, 3, 6, 7, 9],
    link: 1,
    list: [0, 1, 3, 9],
    load: 7,
    local: 1,
    locat: [1, 7],
    logic: 7,
    longer: 7,
    look: 14,
    loop: 14,
    loss: [0, 2, 3, 8, 9],
    ls: 13,
    m: 14,
    made: [7, 8],
    magnifi: 7,
    maintain: 7,
    major: 7,
    make: [1, 7, 8],
    mandat: 7,
    mangl: 13,
    mani: [1, 7],
    manner: 7,
    manual: 7,
    march: 8,
    materi: [0, 3, 9],
    math: 1,
    math2html: 1,
    mathbb: 14,
    mathbf: 14,
    matmul_dot: 14,
    matmul_loop: 14,
    matric: 14,
    maximum: 8,
    may: [0, 1, 7, 8],
    mean: 8,
    mechan: 7,
    medium: 8,
    member: 8,
    memori: 14,
    mention: 7,
    merchant: [0, 2, 3, 6, 8, 9],
    merg: 6,
    messag: 7,
    met: [0, 3, 9],
    method: [1, 7],
    meyer: 5,
    meyerweb: 5,
    might: 7,
    mild: 1,
    miller: 1,
    mini: 7,
    minifi: 13,
    mit: 7,
    modif: [0, 3, 9],
    modifi: [1, 2, 6, 7, 8, 14],
    modul: [1, 12],
    moral: 8,
    mortensen: 1,
    motiv: 8,
    move: 14,
    multipli: 14,
    must: [0, 3, 7, 9],
    n: 14,
    name: [0, 4],
    nation: 8,
    natur: 7,
    near: 1,
    necessari: 8,
    need: 7,
    neglig: [0, 2, 3, 8, 9],
    neighbor: 8,
    nest: 14,
    net: 1,
    new: [1, 7, 14],
    newer: 7,
    next: 7,
    non: [1, 8, 13],
    noninfring: 6,
    note: [5, 7],
    notic: [0, 3, 6, 9],
    nov: 1,
    now: [7, 8],
    nox: 7,
    npm: 13,
    npx: 13,
    number: 8,
    oblig: 8,
    obtain: [6, 8],
    obvious: 7,
    offer: 8,
    onc: 1,
    one: [7, 14],
    onli: 7,
    oper: 14,
    opt: 7,
    option: 7,
    order: 7,
    org: 1,
    origin: [0, 7, 8],
    os: 7,
    osi: 1,
    others: 8,
    otherwis: [0, 1, 3, 5, 6, 8, 9],
    output: [13, 14],
    outsid: 1,
    overt: [1, 8],
    owner: [0, 3, 8],
    p: [1, 14],
    packag: 7,
    paragraph: 8,
    parliament: 8,
    parser: 1,
    part: [1, 8, 14],
    parti: 8,
    partial: [7, 8],
    particular: [0, 3, 6, 7, 8, 9],
    patent: 8,
    path: 7,
    pem: 7,
    perform: [2, 8],
    perman: 8,
    permiss: [0, 2, 6, 8],
    permit: [0, 3, 6, 8, 9],
    perpetu: 1,
    person: [1, 6, 8],
    pertain: 8,
    pick: 7,
    pip: 7,
    pip_self_version_check: 7,
    pkg_resourc: 7,
    place: [1, 7],
    plaintext: 1,
    platform: 7,
    platformdir: 7,
    pleas: [5, 14],
    point: 7,
    popular: 7,
    portabl: 7,
    portion: 6,
    possibl: [0, 3, 7, 8, 9],
    pq: 14,
    pr: [7, 14],
    practic: 7,
    pre: 14,
    prefer: 7,
    prepar: 7,
    present: [1, 8],
    preserv: 8,
    prevent: 7,
    primari: 1,
    prior: 0,
    privaci: 8,
    problem: 7,
    procur: [0, 3, 9],
    product: [0, 8],
    profit: [0, 2, 3, 8, 9],
    project: [1, 8, 9],
    promot: [0, 8],
    prompt: 7,
    protect: 8,
    provid: [0, 1, 2, 3, 6, 8, 9, 14],
    public: 5,
    publish: [6, 7],
    pull: 7,
    punctuation_char: 1,
    pure: 7,
    purpos: [0, 1, 2, 3, 6, 9],
    puzzl: 7,
    py: [1, 7, 14],
    pyopenssl: 7,
    pypi: 7,
    pyproject: 7,
    python: [1, 7, 14],
    pytorch: 14,
    pyvenv: 7,
    q: 14,
    qr: 14,
    quad: 14,
    qualiti: 7,
    question: 14,
    quiet: 8,
    r: 14,
    rather: 7,
    re: 7,
    readi: 7,
    readm: 7,
    reason: [7, 8],
    recent: 7,
    recogn: 1,
    recommend: 1,
    recommonmark_wrapp: 1,
    redistribut: [0, 3, 8, 9],
    redistributor: 7,
    reduc: 7,
    reflect: 7,
    regard: [2, 8],
    regener: 13,
    reinvent: 7,
    reitz: 0,
    releas: [1, 5, 7],
    reli: 7,
    reliabl: 8,
    relicens: 1,
    relinquish: [1, 8],
    remain: 8,
    remaind: 8,
    render: 7,
    replac: [1, 7],
    repositori: 1,
    represent: 8,
    reproduc: [0, 1, 3, 8, 9],
    reput: 8,
    request: 7,
    requir: [1, 7, 8],
    resciss: 8,
    reserv: [0, 1, 9],
    resolv: 7,
    respect: 8,
    respons: 8,
    restrict: [1, 6],
    restructuredtext: [4, 15],
    result: [2, 7, 8],
    retain: [0, 3, 8, 9],
    retir: 1,
    reus: [7, 8, 14],
    reusabl: 7,
    revendor: 7,
    revert: 7,
    review: 7,
    revis: 1,
    revoc: 8,
    right: [0, 1, 6, 9],
    ronach: 0,
    routin: 7,
    royalti: 8,
    rst: [1, 7],
    rst2html5: 1,
    rubric: 12,
    run: 7,
    s: [1, 7, 8, 14],
    s5: 5,
    said: 7,
    sandbox: 1,
    save: 7,
    scientif: 8,
    scratch: 14,
    search: 13,
    second: 7,
    secur: 7,
    see: [1, 4, 5, 9, 15],
    seem: 7,
    self: 7,
    sell: 6,
    semi: 7,
    sensit: 7,
    servic: [0, 3, 9],
    session: 7,
    set: 7,
    setuptool: 7,
    sever: [7, 14],
    sf: 1,
    shall: [0, 2, 3, 6, 8, 9],
    shape: 14,
    shibukawa: 6,
    similar: [7, 8],
    simplejson: 7,
    simpli: 7,
    sinc: 7,
    singl: 7,
    site: 1,
    situat: 7,
    skip: 7,
    slice: 14,
    smartquot: 1,
    smartyp: 1,
    softwar: [0, 1, 2, 3, 6, 7, 8, 9],
    solut: 7,
    solv: 7,
    someon: 7,
    someth: 7,
    sometim: 7,
    somewher: 7,
    sourc: [0, 3, 7, 9],
    sourceforg: 1,
    special: [0, 2, 3, 4, 8, 9],
    specif: 0,
    sphinx: 13,
    src: 14,
    ssl: 7,
    standard: [4, 7],
    start: 7,
    starter: 14,
    state: 1,
    static: 14,
    statutori: 8,
    step: 7,
    sti: 1,
    strict: [0, 3, 9],
    stride: 14,
    strip: 7,
    stylesheet: 1,
    subject: [6, 8],
    sublicens: [6, 8],
    submodul: 7,
    subsequ: 8,
    substanti: 6,
    substitut: [0, 3, 9],
    subvers: 1,
    success: 7,
    successor: [1, 8],
    sum_: 14,
    support: 7,
    surrend: 8,
    svn: 1,
    switch: 7,
    sync: 7,
    syntax: [4, 15],
    sys: 7,
    t: 7,
    take: [7, 8],
    target: 14,
    team: [7, 9],
    technic: 7,
    tendenc: 7,
    term: [1, 7, 8],
    termin: 8,
    territori: 8,
    test: [1, 7, 14],
    test__init__: 1,
    test_code_pars: 1,
    test_direct: 1,
    test_latex2e_misc: 1,
    test_line_length_limit: 1,
    test_line_length_limit_default: 1,
    test_pars: 1,
    test_recommonmark: 1,
    test_rst: 1,
    test_smartquot: 1,
    test_writ: 1,
    tex2mathml_extern: 1,
    text: 1,
    theme: 0,
    theori: [0, 3, 9],
    therefor: 1,
    thereof: 8,
    though: 7,
    throughout: 8,
    time: [7, 8, 14],
    titl: 8,
    toml: 7,
    tool: [1, 5, 7],
    torch: 14,
    tort: [0, 3, 6, 9],
    tortious: [2, 8],
    track: 7,
    trademark: 8,
    tradit: 7,
    transfer: 8,
    transform: 1,
    translat: 8,
    transmit: 1,
    treati: 8,
    tree: 7,
    tri: 14,
    true: 7,
    turner: 8,
    two: [9, 14],
    txt: [4, 7],
    typic: 7,
    ubiqu: 7,
    uglifi: 13,
    uglifyj: 13,
    uncondit: 8,
    underlin: [10, 11, 12],
    underlying: 14,
    understand: [1, 8],
    unfair: 8,
    uninstal: 7,
    unit: 1,
    unknown: 8,
    unless: 9,
    unnecessari: 7,
    unreason: 7,
    unstag: 7,
    updat: 7,
    upgrad: 7,
    upon: [1, 7, 8],
    urllib3: 7,
    us: 1,
    usag: 1,
    use: [0, 1, 2, 3, 4, 6, 7, 8, 9, 14, 15],
    user: 7,
    util: 1,
    v: 7,
    valid: 7,
    variabl: 7,
    ve: 7,
    vector: 14,
    verif: 7,
    version: [1, 7, 8],
    vest: 1,
    via: 7,
    view: 14,
    virtualenv: 7,
    voluntarili: 8,
    waiv: 8,
    warranti: [0, 2, 3, 6, 8, 9],
    wasn: 7,
    way: [0, 1, 3, 7, 9, 14],
    web: 1,
    well: 8,
    whatev: 7,
    whatsoev: [2, 8],
    wheel: 7,
    wheel_dir: 7,
    whether: [0, 1, 2, 3, 6, 8, 9],
    whi: 14,
    whose: 1,
    wide: 1,
    will: [7, 8, 14],
    window: 7,
    wise: 14,
    wish: 8,
    within: 1,
    without: [0, 2, 3, 6, 7, 8, 9],
    work: [0, 1, 7, 8],
    workaround: 7,
    world: [1, 8],
    worldwid: 8,
    write: 7,
    writer: 1,
    written: [0, 14],
    www: 5,
    x: [7, 14],
    xetex: 1,
    y: 14,
    yet: 1,
    yoshiki: 6,
    zero: 1,
  },
  titles: [
    "<no title>",
    "Copying Docutils",
    "Zero-Clause BSD",
    "2-Clause BSD license / FreeBSD license",
    "docutils/parsers/rst/include Directory",
    "<no title>",
    "The MIT License (MIT)",
    "Vendoring Policy",
    "Licence",
    "License for Sphinx",
    "<no title>",
    "<no title>",
    "<no title>",
    "<no title>",
    "Assignment 01: Tensors and Einsum",
    "MLA documentation",
  ],
  titleterms: {
    The: 6,
    abcxi: 14,
    acsxp: 14,
    assign: 14,
    automat: 7,
    bsd: [2, 3, 8],
    bspi: 14,
    cc0: 8,
    claus: [2, 3, 8],
    copi: 1,
    copyright: 8,
    debundl: 7,
    dedic: 1,
    directori: 4,
    disclaim: 8,
    document: 15,
    docutil: [1, 4],
    domain: 1,
    dot: 14,
    einsum: 14,
    except: 1,
    fallback: 8,
    freebsd: 3,
    includ: 4,
    licenc: 8,
    licens: [3, 6, 8, 9],
    limit: 8,
    local: 7,
    manag: 7,
    matrix: 14,
    mit: 6,
    mla: 15,
    modif: 7,
    multipl: 14,
    option: 14,
    parser: 4,
    patch: 7,
    permut: 14,
    polici: 7,
    product: 14,
    public: [1, 8],
    purpos: 8,
    rational: 7,
    relat: 8,
    reshap: 14,
    right: 8,
    rst: 4,
    sphinx: 9,
    statement: 8,
    task: 14,
    tensor: 14,
    universal: 8,
    vendor: 7,
    waiver: 8,
    zero: [2, 8],
  },
});
